Rewire Auth0 Tests 1.1, 1.2 and 2.9
boxwise/dropapp pull request #425
Opened 2021-08-06 17:33 UTC by vahidbazzaz

This PR contains rewiring the auth0 test and tests that check if a user data sync in both Auth0 and DropApp database.

The following is done:
- [X] All of the tests 1.1 completely re-wired and some old tests comment out
- [X] All of the test 1.2  completely re-wired  -  @HaGuesto for these tests, we need to ensure that test users already added in auth0 db
- [ ] Some of 2.9 tests has been completed but 4 tests case 2.9.2, 2.9.4, 2.9.6 and 2.9.8 skipped
- [X] Error page has been changed in order to display more precise error message within different context (a new variable added in config.php called "app_env" and can be set "development", "production" or other context as needed)
- [X] Fixed issue with user redirect after self deactivation of its account
- [X] Changed the loadSessionData to make use of "id" instead of "email" as this causing  an error when users changed its email via cms_profile
- [X] Preventing a user to create new user with the same email address that has already deactivated. (as @jamescrowley also mentioned before, there are some issue in syncing the users between DropApp and Auth0; one example is user deactivation process, where we add ".deleted" suffix to the end of email address in DropApp and this can't be done in Auth0. Also, we should make sure that Auth0 always be considered as source of trust for users which is not the case in current users management)

2021-08-12 18:17 UTC, HaGuesto reviewed
## Code Review
- Write your added settings into config.php.default and the config of circleci
- Write a line in the testing section of the README that you have to change the auth0domain in cypress.json to make tests work locally.
- delete the old 1_2_mobile tests
- hard delete paul at the end of the 2_9 tests



## Functional Review
- Tests 1.1 work
- Test 2.9.5 fails due to deletion typo

2021-08-12 18:18 UTC, HaGuesto commented on library/ajax/testauth0user.php
> +                array_push($validation_result, (!empty($auth0User[0]->blocked) && $auth0User[0]->app_metadata->blocked) ? 'true' : 'false');
here was cause for the failing test 2.9.5. you compared auth0user with db_user

2021-08-14 19:44 UTC, vahidbazzaz commented on assets/js/magic.js
> +
As I have created this branch from my last password PR, this also added it here. But it should be okay as the first PR already merge to master branch.

2021-08-16 07:32 UTC, HaGuesto commented on cypress/integration/2_9_AuthSynchronizedTests.js
> +  let Testname = 'paul';
just a small one. If you are using CamelCase everywhere else then also do it here for name, group, address

2021-08-16 07:34 UTC, HaGuesto commented on mobile.php
> +        throw new Exception('You don\'t have access to this base. Ask your coordinator to correct this!', 403);
Do you think we should go through all "new Exception()" and add error codes?

2021-08-16 07:54 UTC, HaGuesto commented on library/ajax/testauth0user.php
> +                array_push($validation_result, (!empty($auth0User[0]->blocked) && $auth0User[0]->blocked) ? 'true' : 'false');
small thing:
the test would work, but to be 100 % correct you should check something like
```
array_push($validation_result, (!empty($auth0User[0]->blocked) && $auth0User[0]->blocked && (!is_null(db_user['deleted)) || db_user['deleted'] > "0000-00-00") ? 'true' : 'false');
```
This is not tested code, just to show what I would like u to check additionally.

2021-08-16 07:55 UTC, HaGuesto commented on library/ajax/testauth0user.php
> +        $auth_user = getAuth0UserByEmail(preg_match('/\.deleted\.\d+/', $email) ? preg_replace('/\.deleted\.\d+/', '', $email) : $email);
please rename from `auth_user` to something more clear like `auth0_user_unformatted`

2021-08-16 07:56 UTC, HaGuesto commented on library/ajax/testauth0user.php
> +            $auth0User = json_decode($auth_user);
Please either stick with CamelCase for all variables or not. I would suggest renaming this to auth0_user

2021-08-16 07:58 UTC, HaGuesto commented on cypress/plugins/index.js
> +  on('before:browser:launch', (browser = {}, launchOptions) => {
can you explain why this is needed @vahidbazzaz ?

2021-08-16 08:03 UTC, vahidbazzaz commented on mobile.php
> +        throw new Exception('You don\'t have access to this base. Ask your coordinator to correct this!', 403);
@HaGuesto I think it would be good to make errors more informative. One way is to create different exception classes for each kind of errors, and the other way I can think of is to put standard error code in any exceptions. I just added error code for few exceptions that related to this PR.

2021-08-16 08:06 UTC, HaGuesto commented on cypress/integration/2_9_AuthSynchronizedTests.js
> +  let Testaddress = 'pauli@pauli.co';
I would rename this to TestEmail

2021-08-16 08:10 UTC, HaGuesto commented on library/ajax/testdbdelete.php
> +                deleteAuth0UserByEmail($email);
Why are you deleting here by email, @vahidbazzaz? the id is already available and should be the same in Auth0 and the db?

2021-08-16 08:16 UTC, HaGuesto commented on library/lib/session.php
> +function deleteAuth0UserByEmail($email)
maybe this function is not needed since only used in libraray/ajax/testdbdelete.php and there it might be not needed.

2021-08-16 08:27 UTC, HaGuesto commented on cypress/integration/2_9_AuthSynchronizedTests.js
> +
I would like to add here a test if the user changes his password through `cms_profile`. Then we can also chek what happens if the password is not strong enough. 
Test case:
1. got to cms_profile.
2. type in week password just in first field.
3. try to submit (should not work and warning should appear.)
4. type in week password in second pw field.
5. try to submit (should not work and week password warning should appear)
6. type strong password in first pw field.
7. try to submit (should not work and warning of two different passwords should appear.)
8. type strong password in second pw field.
9. submit
10. check if db and auth0 are in sync.
11. change pw back to before.

2021-08-16 08:36 UTC, vahidbazzaz commented on library/ajax/testdbdelete.php
> +                deleteAuth0UserByEmail($email);
@HaGuesto  I just added this to make sure that if the same email available in auth0 anyhow, ensure that is deleted. But since we are not letting the user to use the same email when deactivated, I remove this.

2021-08-16 08:39 UTC, vahidbazzaz commented on cypress/integration/2_9_AuthSynchronizedTests.js
> +
@HaGuesto Sure, please add the test case on the excel file. I will create this test.

2021-08-16 08:40 UTC, HaGuesto commented on include/cms_users_edit.php
> +            redirect('?action=cms_users_edit&origin='.$_POST['_origin'].'&warning=1&message=This email already exists in the system but currently deactivated, please use different email to create a n
Please change message to:
This email already exists in the system but was deactivated. Please use a different email to create a new user!

2021-08-16 08:40 UTC, HaGuesto commented on include/cms_users_edit.php
> +            redirect('?action=cms_users_edit&origin='.$_POST['_origin'].'&warning=1&message=This email already exists in the system but currently deactivated, please use different email to create a n
Please change message to:
This email already exists in the system but was deactivated. Please use a different email to create a new user!

2021-08-16 08:41 UTC, vahidbazzaz commented on cypress/integration/2_9_AuthSynchronizedTests.js
> +  let Testaddress = 'pauli@pauli.co';
Sure, I will change and put this in cypress.json environment variables.

2021-08-16 08:51 UTC, HaGuesto commented on include/cms_users_edit.php
> +                redirect('?action=cms_users&warning=1&message=This email already exists in another organisation.<br>Please use a different email to create a new user!');
I added this line

2021-08-16 08:53 UTC, vahidbazzaz commented on cypress/plugins/index.js
> +  on('before:browser:launch', (browser = {}, launchOptions) => {
@HaGuesto I forgot to remove this. Actually this is no longer needed as we set chromeWebSecurity in cypress.json

2021-08-16 08:54 UTC, vahidbazzaz commented on include/cms_users_edit.php
> +            redirect('?action=cms_users_edit&origin='.$_POST['_origin'].'&warning=1&message=This email already exists in the system but currently deactivated, please use different email to create a n
Sure

2021-08-16 08:56 UTC, HaGuesto commented on include/cms_users_edit.php
> -                redirect('?action=cms_users&warning=1&message=This email already exists in another organisation.<br>Please ask the corresponding person to deactivate their other account!');
This should be reported to sentry as a NOTICE
u can do this with:
`trigger_error('message', E_USER_NOTICE)'

2021-08-16 08:56 UTC, HaGuesto commented on include/cms_users_edit.php
>                  redirect('?action=cms_users&warning=1&message=This email already exists in your organisation. You do not have access to this account.');
This should be reported to sentry as a NOTICE
u can do this with:
`trigger_error('message', E_USER_NOTICE)'

2021-08-16 08:57 UTC, HaGuesto commented on include/cms_users_edit.php
>                  redirect('?action=cms_users_edit&id='.$existinguser['id'].'&origin='.$_POST['_origin'].'&warning=1&message=This email already exists in your organisation. You are forwarded to the cor
This should be reported to sentry as a NOTICE
u can do this with:
`trigger_error('message', E_USER_NOTICE)'

2021-08-16 08:57 UTC, HaGuesto commented on include/cms_users_edit.php
> +            redirect('?action=cms_users_edit&origin='.$_POST['_origin'].'&warning=1&message=This email already exists in the system but currently deactivated, please use different email to create a n
This should be reported to sentry as a NOTICE
u can do this with:
`trigger_error('message', E_USER_NOTICE)'

2021-08-16 08:57 UTC, HaGuesto commented on include/cms_users_edit.php
> +            redirect('?action=cms_users_edit&origin='.$_POST['_origin'].'&warning=1&message=This email already exists in the system but currently deactivated, please use different email to create a n
This should be reported to sentry as a NOTICE
u can do this with:
`trigger_error('message', E_USER_NOTICE)'

2021-08-16 08:58 UTC, HaGuesto commented on library/lib/errorhandling.php
> +    // if ('localhost' == @parse_url('http://'.$_SERVER['HTTP_HOST'], PHP_URL_HOST)) {
remove quotes

2021-08-16 09:02 UTC, HaGuesto commented on library/lib/session.php
> +        // $error = new Zmarty();
remove quotes

2021-08-16 09:04 UTC, HaGuesto commented on library/lib/session.php
> +            //$responseBodyAsString = $response->getBody()->getContents();
remove quote

2021-08-16 09:07 UTC, HaGuesto requested changes
Only tiny things left @vahidbazzaz 

## code review
in comments in the code

## functional review
- [x] error trace only appears in development mode
- [x] blocking the creation of new users with already existing emails works
- [x] self-deactivation works

2021-08-16 09:08 UTC, vahidbazzaz commented on library/lib/errorhandling.php
> +    // if ('localhost' == @parse_url('http://'.$_SERVER['HTTP_HOST'], PHP_URL_HOST)) {
@HaGuesto remove the commented codes? right?

2021-08-16 09:23 UTC, HaGuesto commented on library/lib/errorhandling.php
> +    // if ('localhost' == @parse_url('http://'.$_SERVER['HTTP_HOST'], PHP_URL_HOST)) {
yes

2021-08-16 09:24 UTC, HaGuesto commented on library/lib/errorhandling.php
> +    // if ('localhost' == @parse_url('http://'.$_SERVER['HTTP_HOST'], PHP_URL_HOST)) {
if i wrote quotes somewhere else i meant commented lines

2021-08-16 09:26 UTC, HaGuesto commented on cypress/integration/2_9_AuthSynchronizedTests.js
> +
done

2021-08-16 09:27 UTC, HaGuesto commented on mobile.php
> +        throw new Exception('You don\'t have access to this base. Ask your coordinator to correct this!', 403);
i will make a ticket out of it

2021-08-16 09:34 UTC, vahidbazzaz commented on library/lib/errorhandling.php
> +    // if ('localhost' == @parse_url('http://'.$_SERVER['HTTP_HOST'], PHP_URL_HOST)) {
Sure

2021-08-16 09:36 UTC, vahidbazzaz commented on library/ajax/testauth0user.php
> +            $auth0User = json_decode($auth_user);
Sure I will correct styling and formatting

2021-08-17 06:27 UTC, HaGuesto commented on cypress/integration/2_9_AuthSynchronizedTests.js
> +
we change the flow for 10.

we do 
10. logout
11. check if you can login with new password

2021-08-17 13:52 UTC, vahidbazzaz commented on include/cms_users_edit.php
> +                redirect('?action=cms_users&warning=1&message=This email already exists in another organisation.<br>Please use a different email to create a new user!');
I also change and merge to remote branch

2021-08-17 13:52 UTC, vahidbazzaz commented on cypress/integration/2_9_AuthSynchronizedTests.js
> +
I have added the test with all the steps per your suggestion

2021-08-21 09:13 UTC, HaGuesto commented on cypress/integration/1_1_LoginTests.js
> +  Cypress.config('defaultCommandTimeout',200000);
Why did you put a timeout here? @vahidbazzaz

2021-08-21 09:34 UTC, vahidbazzaz commented on library/lib/session.php
> +        // $error = new Zmarty();
done

2021-08-21 09:35 UTC, vahidbazzaz commented on library/lib/session.php
> +            //$responseBodyAsString = $response->getBody()->getContents();
done

2021-08-21 09:36 UTC, vahidbazzaz commented on cypress/integration/1_1_LoginTests.js
> +  Cypress.config('defaultCommandTimeout',200000);
discussed

2021-08-21 14:54 UTC, HaGuesto approved these changes
I think we have done it @vahidbazzaz

2021-08-21 14:55 UTC, merged

2021-08-21 14:56 UTC, HaGuesto commented
![](https://github.trello.services/images/mini-trello-icon.png) [Write tests 2.9 to check auth0 sync](https://trello.com/c/4AM4LHqe/731-write-tests-29-to-check-auth0-sync)

2021-08-21 15:09 UTC, HaGuesto commented
![](https://github.trello.services/images/mini-trello-icon.png) [Re-wire all authentication test 1.1](https://trello.com/c/qyraA0Ba/732-re-wire-all-authentication-test-11)

2021-08-21 15:09 UTC, HaGuesto commented
![](https://github.trello.services/images/mini-trello-icon.png) [validation of second password field in cms_profile](https://trello.com/c/aywHAqRa/733-validation-of-second-password-field-in-cmsprofile)