Update Auth0 Authentication ADR
boxwise/dropapp pull request #434
Opened 2021-09-25 13:07 UTC by vahidbazzaz

This PR revised the current Auth0 Authentication ADR by adding recent changes and minimal update

2021-09-25 14:25 UTC, aerinsol requested changes
Two of the key points in your doc comparison is that pricing is an issue once we hit 10K (users? verifications? what's the rate limit unit here?) 

So we should capture that point under "harder".

2021-09-25 14:28 UTC, vahidbazzaz commented
> Two of the key points in your doc comparison is that pricing is an issue once we hit 10K (users? verifications? what's the rate limit unit here?)
> 
> So we should capture that point under "harder".

@aerinsol Sure, thanks that make sense and I will update it accordingly.

2021-09-26 09:22 UTC, aerinsol commented on docs/adr/adr_auth0.md
>  - Auth0 and Google Firebase comparison in detail [https://docs.google.com/document/d/1sWmS_VDHDx3VDX7JFu78fpU8yMF9eUOHvp2PqJ9_dy0/edit?usp=sharing]
@vahidbazzaz as mentioned before please put this in "Considered Options"

2021-09-26 09:22 UTC, aerinsol commented on docs/adr/adr_auth0.md
> +- Changes to the current Auth0 enterprise agreement for open source project
What are the changes and why should we be concerned?

2021-09-26 09:23 UTC, aerinsol requested changes
Still not totally clear.

2021-09-26 09:23 UTC, aerinsol commented on docs/adr/adr_auth0.md
> +- Reaching the total users (10K) or API rate limits, and how they impact pricing
Should this say "becomes much more expensive at a rate of $XXX instead of $YYY from comparable solutions". The goals of this ADR Is that people can read this and understand the conclusion and how bad the problem is, without digging around.

2021-09-26 09:26 UTC, vahidbazzaz commented on docs/adr/adr_auth0.md
> +- Changes to the current Auth0 enterprise agreement for open source project
@aerinsol Please recheck the most recent version since you seem to have commented on an outdated version of the file. I already addressed that concern regarding pricing.

2021-09-26 09:33 UTC, vahidbazzaz commented on docs/adr/adr_auth0.md
>  - Auth0 and Google Firebase comparison in detail [https://docs.google.com/document/d/1sWmS_VDHDx3VDX7JFu78fpU8yMF9eUOHvp2PqJ9_dy0/edit?usp=sharing]
@aerinsol Could you please confirm that the following is aligned with what you mentioned:

- Good Docs and Supports
- Comparison Auth0 and Google Firebase

2021-09-27 00:29 UTC, aerinsol approved these changes

2021-11-27 19:54 UTC, merged