Feature/org creation roles sync auth0
boxwise/dropapp pull request #464
Opened 2022-02-23 15:53 UTC by vahidbazzaz

2022-02-24 19:27 UTC, vahidbazzaz commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implement roles/permissions/db permissions in dropapp](https://trello.com/c/HgKoMDov/811-implement-roles-permissions-db-permissions-in-dropapp)

2022-02-26 11:36 UTC, vahidbazzaz commented
NOTE: We need to make sure the test users aren't affected by this PR (synchronizing existing roles with auth0)

2022-02-26 11:44 UTC, aerinsol commented
Specifically Hermine test users for the production read access API

On Sat, Feb 26, 2022, 7:36 PM Vahid Bazzaz ***@***.***> wrote:

> NOTE: We need to make sure the test users aren't affected by this PR
> (synchronizing existing roles with auth0)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/boxwise/dropapp/pull/464#issuecomment-1052051543>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABP2BFCMYVOXJYXFIACM25LU5C3L7ANCNFSM5PEYNYRQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-03-03 07:43 UTC, HaGuesto commented on db/seeds/ActionPermissions.php
> +        $this->execute('UPDATE cms_functions SET action_permissions = "checkout_beneficiaries" WHERE id=87');
note for Hans Review: do we need this in the migration?

2022-03-03 07:44 UTC, HaGuesto commented on include/camps_edit.php
> -    addfield('select', 'Functions available for this base', 'functions', ['width' => 6, 'tab' => 'general', 'multiple' => true, 'query' => '
note for Hans review: How does the disabling work?

2022-03-03 07:45 UTC, HaGuesto commented on include/cms_usergroups.php
>              case 'delete':
Hans review: check all cases for usergroups edit

2022-03-03 07:53 UTC, HaGuesto commented on reseed-auth0-roles.php
> +<?php
put this file into reseed-auth0

2022-03-03 07:54 UTC, HaGuesto commented on library/lib/auth0.php
> + * Getting all avialble End-Points in Auth0.
remove resource stuff if it is not needed.

2022-03-27 14:59 UTC, HaGuesto commented on library/constants.php
> +$menusToActions = [
@vahidbazzaz is this constant still needed?

2022-03-27 15:45 UTC, HaGuesto commented on library/lib/auth0.php
> +        // user doesn't exist in auth0
I do not like the error handling here. Looks very copy/paste

2022-03-27 17:01 UTC, HaGuesto commented on library/lib/auth0.php
> +        assignRolesToUser($auth0UserId, $roles);
It feels like it always adds the roles before checking if they are already assigned.

2022-03-27 17:05 UTC, HaGuesto requested changes
# Review
@vahidbazzaz I decided to check the different bullet points one by one for the functionalreview. The code review I comment inline

## functional review:
(0.) db migrations and seeds
migration works and can be reverted. It looks good.
For the seed I had to add some permissions, but it looks good now.

1. Remove access of users to usergroups menu to not get the mapping to roles out of sync
That's done in production. I just checked again.

2. create all roles in Auth0 based on the dev seed db (bases, organisation). This should be about 7 roles per base. 
In dev all roles are there. In staging there are some missing, but we can test the script you wrote once it is merged.
At some point you need to explain to me again why there is only one administrator role for all orgs.

3. create functions for dynamic creation of roles in Auth0 if an organisation is created. (Admin role only) 
write function when first base is created. There should be 7 usergroups in dropapp created and 5 roles in Auth0. DO NOT forget to write entries for usergroups in cms_usergroups_functions and cms_usergroups_camps

This works fine. I'm a bit concerned if we should really use the global variable $menusToActions or just query the menues from action_permissions in cms_functions.
We also need to go through the error handling in some of the functions in auth0.php

4. create functions for dynamic creation of roles in Auth0 if an base is created.
write function when second to nth base is created. There should be 6 usergroups in dropapp created (no admin) and 5 roles in Auth0. DO NOT forget to write entries for usergroups in cms_usergroups_functions and cms_usergroups_camps and set userlevel. DO NOT forget to assign a new base to the admin usergroup
Works fine. Same comments as for 3.)

5. create db table cms_usergroups_roles which tracks the mapping of usergroups to Auth0 roles.
works fine.

6. add roles to cms_functions (write db migration for production and add a form field in cms_functions_edit to access this field)
This works and I added also a column to show the permissions in the table of cms_functions.

8. create a test function which can be run by a cron job that checks every night if all roles exist in Auth0 that are needed according to the db bases and organisation and cms_usergroups_roles. (check if roles are in sync to bases and organisations).
This is missing.

9. when a user is created, edited or deleted assign the roles according to cms_usergroups_roles in Auth0.
This only adds new roles to a user in Auth0, but does not remove old ones.

11. update cron job test if all users are in sync between Auth0 and the db to now also check if if the users roles are in sync with the usergroup of the dropapp.
This works, but we need to add a seed for cms_usergroups_roles.

12. disable renaming of usergroups
This does not work.

13. disable delete of usergroups
This works

14. if base is renamed, rename the user group names
This works. The problem is that if old usergroup names are renamed it creates problems.

15. disable delete of bases
I edited this a bit.

16. disable delete of organisations 
I edited this a bit.

17. create all standard auth0 roles, which are created usually new bases/organisations, also for each existing base/organisation; we do this by running parts of the auth0-reseed cron job (not the password reset) against production; for this we create a script similiar to auth0-reseed, add it as an entrypoint in gcloud-entry and add a line in cron.yaml. when it is live we can trigger the script through google appengine.
I have not checked this.

2022-03-27 18:09 UTC, HaGuesto commented on db/auth0/create-auth0-roles-usergroups.php
> +updateResources('5ef3760527b0da00215e6209', $methods);
this needs to be replaced by a $settings variable which need to be set in CircleCI

2022-03-27 18:10 UTC, HaGuesto commented on db/auth0/create-auth0-roles-usergroups.php
> +    $permittedDatabases = ['dropapp_dev', 'dropapp_demo', 'dropapp_staging'];
remove these line

2022-03-27 18:23 UTC, HaGuesto commented
Summary: What is left to be done?

1. If a user is edited and a different usergroup is assigned, the role in auth0 schould not just be assigned, but also the old roles removed.
2. disable name field in usergroups_edit
3. fix renaming bases of already existing bases.
4. fix [db/auth0/create-auth0-roles-usergroups.php](https://github.com/boxwise/dropapp/pull/464/files#diff-f4f607b96340f67e911c92592787a783aa15c35949d5569bf5468b8d795fc816) by adding cron job and entrypoint
5. @HaGuesto decide how when to run the scripts reseed-auth0 and resee-roles-auth0.


What do we move to a different ticket?
- We need to rework the dev seed so that the usergroups in the seed are connected with the roles in Auth0 on local dev environments and staging.
- maybe exchange $menusToActions by a query to cms_functions.

2022-03-28 11:32 UTC, vahidbazzaz commented on db/auth0/create-auth0-roles-usergroups.php
> +    $permittedDatabases = ['dropapp_dev', 'dropapp_demo', 'dropapp_staging'];
@HaGuesto I remove database name checking but keep the first few lines to ensure that this script only run via cron job.

2022-03-28 11:34 UTC, vahidbazzaz commented on db/auth0/create-auth0-roles-usergroups.php
> +updateResources('5ef3760527b0da00215e6209', $methods);
@HaGuesto I have added environment variables in the CircleCi and now using $settings to bind the value

2022-03-28 14:50 UTC, vahidbazzaz commented on library/lib/auth0.php
> +        assignRolesToUser($auth0UserId, $roles);
@HaGuesto  I fixed this by removing the roles at first hands and then adding new roles.

2022-03-28 14:53 UTC, vahidbazzaz commented
@HaGuesto Thanks for the review, I made the changes as per your suggestions.

2022-03-29 13:12 UTC, vahidbazzaz commented on library/lib/auth0.php
> +        // user doesn't exist in auth0
@HaGuesto I have improved the exception handling

2022-03-29 13:15 UTC, vahidbazzaz commented on library/constants.php
> +$menusToActions = [
@HaGuesto I will implement query version in  the different ticket as we discussed

2022-04-23 14:01 UTC, HaGuesto approved these changes
Hey @vahidbazzaz Vahid, locally all tests work and I do not see any big flaws on first sight. I'm gonna merge on master and will do some more tests there.

/Hans

2022-04-23 14:08 UTC, merged