Prevent Duplicates QR labels Print
boxwise/dropapp pull request #469
Opened 2022-03-15 15:12 UTC by vahidbazzaz

This PR adds a page number to the footer on the PDF generation to make sure it is not a printer repeat error.

2022-03-15 15:16 UTC, vahidbazzaz commented
![](https://github.trello.services/images/mini-trello-icon.png) [There are duplicate QR codes generated if you generate more than 20 or 30 at once](https://trello.com/c/OjWZzsGA/850-there-are-duplicate-qr-codes-generated-if-you-generate-more-than-20-or-30-at-once)

2022-03-15 18:00 UTC, aerinsol requested changes

2022-03-15 18:00 UTC, aerinsol commented on pdf/pdf.php
> +        $this->SetFont('Arial', 'I', 6);
Open Sans (per our brand identity guidelines) please.

2022-03-16 08:25 UTC, vahidbazzaz commented on pdf/pdf.php
> +        $this->SetFont('Arial', 'I', 6);
@aerinsol Since we were previously using Helvetica in the PDF, I have incorporated Open Sans fonts in accordance with your recommendation and our brand identity guidelines, and updated the file accordingly.

2022-03-17 13:01 UTC, aerinsol approved these changes

2022-04-04 12:50 UTC, aerinsol approved these changes

2022-04-04 12:50 UTC, merged