Creation of Other Admin Accounts for Organization
boxwise/dropapp pull request #472
Opened 2022-03-19 09:27 UTC by vahidbazzaz

The PR adds the required change that allows admins in an organization to create additional admin accounts.

2022-03-19 09:28 UTC, vahidbazzaz commented
![](https://github.trello.services/images/mini-trello-icon.png) [Creation of Other Admin Accounts for my organization](https://trello.com/c/YAF3Az4P/668-creation-of-other-admin-accounts-for-my-organization)

2022-03-19 11:20 UTC, aerinsol approved these changes

2022-03-27 18:37 UTC, HaGuesto commented
drop $admin_allowed and change $userlevel_allowed like you do in the query in line 125

2022-04-04 18:30 UTC, aerinsol requested changes
see @HaGuesto comment

2022-04-07 15:45 UTC, aerinsol approved these changes

2022-04-07 15:45 UTC, merged