Tags for Boxes, shared with Beneficiaries
boxwise/dropapp pull request #483
Opened 2022-05-20 06:44 UTC by vahidbazzaz

This PR contains the changes to support unified tags for the Beneficiaries and Boxes.

2022-05-20 06:46 UTC, vahidbazzaz commented
![](https://github.trello.services/images/mini-trello-icon.png) [Tags for Boxes, shared with Beneficiaries #large](https://trello.com/c/XjNwO3sL)

2022-05-26 14:03 UTC, aerinsol commented on include/people_edit.php
> +        [$message, $id] = db_transaction(function () use ($table, $settings) {
confused. How does this relate to tags?

2022-05-26 14:08 UTC, aerinsol commented on include/people_edit.php
> +            tags ON tags.id = tags_relations.tag_id AND tags_relations.object_type = "People" AND tags.deleted IS NULL
When did we add a deleted field to tags?

2022-05-26 15:48 UTC, aerinsol commented on include/tags.php
> +                    define('BOX_WARNING', 'Changing the apply to will remove those tags once it has been saved, as there are about '.$boxesCount.' boxes that applied tags');
Box warning: 'WARNING: Changing the tag type will remove '.$boxesCount.' existing tags from boxes."

2022-05-26 15:49 UTC, vahidbazzaz commented on include/people_edit.php
> +            tags ON tags.id = tags_relations.tag_id AND tags_relations.object_type = "People" AND tags.deleted IS NULL
@aerinsol this is removal tags that sometime ago we added https://trello.com/c/no6uIJAr

2022-05-26 15:50 UTC, aerinsol commented on include/tags.php
> +                    define('PEOPLE_WARINING', 'Changing the apply to will remove those tags once it has been saved, as there are about '.$beneficiariesCount.' beneficiaries that applied tags');
`define ('PEOPLE_WARNING'` is misspelled. 

Also, recommended warning text: 'WARNING: Changing the tag type will remove '.$beneficiariesCount.' existing tags that have been applied to beneficiaries."

2022-05-26 15:55 UTC, aerinsol requested changes
Nicely done! Just a few small change requests on my side. Also, I think I noticed that for the badge displays in the "Edit Boxes" views, the tags seem to appear in reverse order to what they appear like in the "Manage Boxes" view. Can you check that? @vahidbazzaz

2022-05-26 15:56 UTC, vahidbazzaz commented on include/people_edit.php
> +        [$message, $id] = db_transaction(function () use ($table, $settings) {
@aerinsol Just wrapping the transactions over the entire queries while editing beneficiaries (including the tags applied)

2022-05-27 09:25 UTC, aerinsol approved these changes

2022-06-03 10:30 UTC, HaGuesto commented on include/stock_edit.php
> +                LEFT JOIN tags ON tags.id = tags_relations.tag_id
tags.deleted

2022-06-04 07:39 UTC, HaGuesto commented on include/stock_edit.php
> +    $cmsmain->assign('peopletitle', 'Box ');
we renamed it but it works generally

2022-06-04 13:23 UTC, HaGuesto approved these changes

2022-06-09 13:29 UTC, merged