Part 1 - Mobile Distro DB Migrations
boxwise/dropapp pull request #499
Opened 2022-07-23 07:42 UTC by vahidbazzaz

This PR contains the migrations needed for round 1 of the mobile distro feature. 

Ref. doc: https://docs.google.com/document/d/144pHmdgkusbnbSgatyHAeeU34gFiWLYOI2puT_CA6ws/edit#

2022-07-23 07:43 UTC, vahidbazzaz commented
![](https://github.trello.services/images/mini-trello-icon.png) [Mobile Distro: Needed DB Migrations - Round 1](https://trello.com/c/nEidtRbT)

2022-07-23 11:22 UTC, HaGuesto requested changes
@vahidbazzaz general comments:
- if u are setting NULL to false for a column, please define what the default value should be.
- what are all these indices for? I would only create an index if u filter or join by a column. 
- Also does it not automatically create an index if u introduce a foreign key?

2022-07-23 11:22 UTC, HaGuesto commented on db/migrations/20220722085453_dirstro_events_table.php
> +            'engine' => 'InnoDB',
Why did u define engine, encoding and collation? The defaults should be fine. And encoding should be utf8, right?

2022-07-23 11:22 UTC, HaGuesto commented on db/migrations/20220722085453_dirstro_events_table.php
> +                'null' => false,
If Null is falsche, what is the default?

2022-07-23 11:22 UTC, HaGuesto commented on db/migrations/20220722085453_dirstro_events_table.php
> +                'null' => false,
If Null is false, what is the default?

2022-07-23 11:22 UTC, HaGuesto commented on db/migrations/20220722085453_dirstro_events_table.php
> +                'null' => false,
If Null is falsche, what is the default?

2022-07-23 11:22 UTC, HaGuesto commented on db/migrations/20220723052618_dirstro_events_packing_list_entries.php
> +            'comment' => '',
What is this for?

2022-07-23 11:22 UTC, HaGuesto commented on db/migrations/20220723052618_dirstro_events_packing_list_entries.php
> +            'engine' => 'InnoDB',
Same comment as before

2022-07-23 11:29 UTC, vahidbazzaz commented on db/migrations/20220723052618_dirstro_events_packing_list_entries.php
> +            'comment' => '',
@HaGuesto I have added this to ensure our configuration matches the peewee in the new app, but if it needs to be changed, please feel free to do so.

2022-07-23 11:30 UTC, vahidbazzaz commented on db/migrations/20220722085453_dirstro_events_table.php
> +                'null' => false,
@HaGuesto  I have added them based on the ref docs, please refer to docs and suggest your changes as needed

2022-07-23 11:43 UTC, vahidbazzaz commented on db/migrations/20220722085453_dirstro_events_table.php
> +                'null' => false,
@HaGuesto  In this case, the value should never be null, so why do you think there should be a default value?

2022-07-23 11:43 UTC, vahidbazzaz commented on db/migrations/20220722085453_dirstro_events_table.php
> +                'null' => false,
@HaGuesto  the value should never be null, so why do you think there should be a default value?

2022-07-23 11:45 UTC, vahidbazzaz commented on db/migrations/20220723052618_dirstro_events_packing_list_entries.php
> +            'comment' => '',
@HaGuesto This is not so important, but make sure this matches peewee's configuration.

2022-07-23 11:45 UTC, vahidbazzaz commented on db/migrations/20220723052618_dirstro_events_packing_list_entries.php
> +            'engine' => 'InnoDB',
@HaGuesto also same answer for this

2022-07-23 11:47 UTC, vahidbazzaz commented on db/migrations/20220722085453_dirstro_events_table.php
> +                'null' => false,
@HaGuesto  why do you think there should be a default value? this is a mandatory field

2022-07-23 12:33 UTC, vahidbazzaz commented
@HaGuesto Thanks for your review, please find my answers to your comments:
- The encoding, collations, and engine were removed from table definitions, but please note that this was the norm in previous migrations!
- In my opinion, mandatory fields should not always have default values. It would be helpful if you could provide your changes to the reference documents if you believe there is a case.
- I removed the extra indexes for foreign key fields per your suggestion, but kept the ones that can be filtered out in queries

2022-07-23 12:45 UTC, pylipp commented on db/migrations/20220722085453_dirstro_events_table.php
> +            'engine' => 'InnoDB',
FYI `utf8` is a deprecated alias in MySQL 8.0

https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-sets.html

2022-07-23 12:53 UTC, vahidbazzaz commented
@pylipp thanks for your comment regarding the `utf8` encoding, I have checked the mysql docs again and while it says that `utf8` is deprecated but it also mentioned it will become an alias for `utf8mb4` in the future:

`utf8: An alias for utf8mb3. In MySQL 8.0, this alias is deprecated; use utf8mb4 instead. utf8 is expected in a future release to become an alias for utf8mb4.`

2022-07-23 13:55 UTC, aerinsol commented
I don't agree with not putting in indices (indexes). It's not like putting
in indices is very expensive and if you already know there's going to be a
lot of filtering / queries run against a table that aren't joined or
retrieved by the PK, it makes sense.

On Sat, Jul 23, 2022 at 8:53 PM Vahid Bazzaz ***@***.***>
wrote:

> @pylipp <https://github.com/pylipp> thanks for your comment regarding the
> utf8 encoding, I have checked the mysql docs again and while it says that
> utf8 is deprecated but it also mentioned it will become an alias for
> utf8mb4 in the future:
>
> utf8: An alias for utf8mb3. In MySQL 8.0, this alias is deprecated; use
> utf8mb4 instead. utf8 is expected in a future release to become an alias
> for utf8mb4.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/boxwise/dropapp/pull/499#issuecomment-1193120883>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABP2BFGTR2ORTQKPC6PEQO3VVPTN3ANCNFSM54NTBWUA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-07-23 15:17 UTC, HaGuesto commented
@Vahid:
- you are correct about the defaults. I just did a quick first review from my phone and did not check the ref. Sorry for that.
- I will check what the right way is regarding regarding collation, encoding and engine.

@aerinsol:
Regarding the indices: I agree to have indices on the FOREIGN KEY columns, but  they are created automatically for a column if you add a foreign key constraint. You can define indices yourself, but this is obsolete if you add a FOREIGN KEY constraint for the same column. So, this is is not a important point. WE can explicitly mention the indices in the migration or we can leave them out. I do not have a strong opinion

[For reference](https://dev.mysql.com/doc/refman/8.0/en/constraint-foreign-key.html)
> MySQL requires that foreign key columns be indexed; if you create a table with a foreign key constraint but no index on a given column, an index is created.

2022-07-23 15:59 UTC, HaGuesto commented
@vahidbazzaz one change request I have:
can u please do two things around the `created_by` column:
- allow NULL
- make the DELETE case in the FOREIGN KEY CONSTRAINT `SET_NULL`

For GDPR reasons we need to be able to fully delete a user in our database and their references in the data. We could solve this by changing this reference to go to another user, but we do not do it with any other created_by column in all other tables and I would like to keep it that way.

2022-07-24 10:51 UTC, HaGuesto commented on db/migrations/20220723052618_dirstro_events_packing_list_entries.php
> +                'update' => 'CASCADE',
@vahidbazzaz Why did you not add an delete case here?

2022-07-24 10:52 UTC, HaGuesto commented on db/migrations/20220723060012_dirstro_events_unboxed_item_collections.php
> +                'update' => 'CASCADE',
same here?

2022-07-24 10:52 UTC, vahidbazzaz commented on db/migrations/20220723052618_dirstro_events_packing_list_entries.php
> +                'update' => 'CASCADE',
@HaGuesto because we don't want to have soft delete for this table as we discussed with @spaudanjo

2022-07-24 10:52 UTC, HaGuesto commented on db/migrations/20220723061731_dirstro_events_outflow_logs.php
> +                'update' => 'CASCADE',
and here

2022-07-24 10:54 UTC, vahidbazzaz commented on db/migrations/20220723060012_dirstro_events_unboxed_item_collections.php
> +                'update' => 'CASCADE',
@HaGuesto same here, please refer to docs

2022-07-24 10:56 UTC, HaGuesto commented on db/migrations/20220723052618_dirstro_events_packing_list_entries.php
> +                'update' => 'CASCADE',
Then u need to set delete to CASCADE. because if you do not define it it actually works like a RESTRICT

2022-07-24 10:56 UTC, vahidbazzaz commented on db/migrations/20220723060012_dirstro_events_unboxed_item_collections.php
> +                'update' => 'CASCADE',
@HaGuesto same here

2022-07-24 10:57 UTC, vahidbazzaz commented on db/migrations/20220723052618_dirstro_events_packing_list_entries.php
> +                'update' => 'CASCADE',
@HaGuesto ok sure

2022-07-24 11:35 UTC, HaGuesto approved these changes
# functional review
I went through the ref doc and checked if all fields were created correctly.

## locations
- [x]  `type` varchar(20) NOT NULL DEFAULT 'Warehouse’,^M
- [x]  `latitude` double DEFAULT NULL,^M
- [x]  `longitude` double DEFAULT NULL,^M
- [x]  `description` varchar(255) DEFAULT NULL,^M
- [x] rollback

## stock

- [x] `distro_event_id` int unsigned DEFAULT NULL,
- [x] foreign key
- [x] rollback

## distro_events

- [x]  `id` int unsigned NOT NULL AUTO_INCREMENT,^M
- [x]`name` varchar(255) DEFAULT NULL,^M
- [x]  `planned_start_date_time` datetime NOT NULL,^M
- [x] `planned_end_date_time` datetime NOT NULL,^M
- [x]  `location_id` int unsigned NOT NULL,^M
- [x]  `state` varchar(255) NOT NULL DEFAULT 'Planning',^M
- [x]  `created_on` datetime NOT NULL,^M
- [x]  `created_by` int unsigned DEFAULT NULL,^M
- [x]  `deleted_on` datetime DEFAULT NULL,^M
- [x]  `modified_on` datetime DEFAULT NULL,^M
- [x]  `modified_by` int unsigned DEFAULT NULL,^M
- [x] foreign key
- [x] rollback

## distro_event_packing_list_entries

- [x]  `id` int unsigned NOT NULL AUTO_INCREMENT,^M
- [x]  `product_id` int unsigned NOT NULL,^M
- [x]  `number_of_items` int NOT NULL,^M
- [x]  `size_id` int unsigned NOT NULL,^M
- [x]  `distro_event_id` int unsigned NOT NULL,^M
- [x]  `state` varchar(255) NOT NULL,^M
- [x]  `created_on` datetime DEFAULT NULL,^M
- [x]  `created_by` int unsigned DEFAULT NULL,^M
- [x]  `modified_on` datetime DEFAULT NULL,^M
- [x]  `modified_by` int unsigned DEFAULT NULL,^M
- [x] foreign key
- [x] rollback

## distro_events_unboxed_item_collections` (

- [x]  `id` int unsigned NOT NULL AUTO_INCREMENT,
- [x]  `product_id` int unsigned NOT NULL,
- [x]  `size_id` int unsigned NOT NULL,
- [x]  `number_of_items` int NOT NULL,
- [x]  `distro_event_id` int unsigned NOT NULL,
- [x] `location_id` int unsigned NOT NULL,
- [x]  `comments` text DEFAULT NULL,
- [x]  `created` datetime DEFAULT NULL,
- [x]  `created_by` int unsigned DEFAULT NULL,
- [x]  `modified_on` datetime DEFAULT NULL,
- [x]  `modified_by` int unsigned DEFAULT NULL,
- [x]  `box_state_id` int unsigned NOT NULL DEFAULT '1',
- [x] foreign key
- [x] rollback

## distro_events_outflow_logs

- [x]  `id` int unsigned NOT NULL AUTO_INCREMENT,
- [x]   `product_id` int unsigned NOT NULL,
- [x]  `size_id` int unsigned NOT NULL,
- [x]  `number_of_items` int NOT NULL,
- [x]  `date` datetime NOT NULL,	
- [x]  `location_id` int unsigned NOT NULL,
- [x]  `distro_event_id` int unsigned DEFAULT NULL,
- [x]  `details` text DEFAULT NULL
- [x] foreign key
- [x] rollback
- I removed the created and modified fiels since they are not needed for logs and not in the ref document

2022-07-24 11:36 UTC, HaGuesto approved these changes
@vahidbazzaz thanks for the last changes

code review is now also approved

2022-07-24 11:36 UTC, merged