Add moved-boxes SQL query for annual report
boxwise/dropapp pull request #579
Opened 2024-03-04 17:03 UTC by pylipp

2024-03-15 10:17 UTC, aerinsol commented
as discussed with @HaGuesto, this needs to be revised to cover

- Boxes created in donated locations (although tbh, this is arguable)
- Boxed created before 2023 but moved after 2023
- Boxes from archived locations.

2024-03-17 18:10 UTC, aerinsol requested changes
As mentioned in the PR, needs corrections for accuracy.

2024-03-18 14:22 UTC, pylipp commented
![](https://github.trello.services/images/mini-trello-icon.png) [2.0 Improve moved-boxes statistics](https://trello.com/c/7b4VD48d/1386-20-improve-moved-boxes-statistics)

2024-03-18 15:14 UTC, aerinsol commented on db/queries/annual_report.sql
> +    AND ((h.to_int IS NOT null AND h.id >= 1324559) OR h.changes = "Record created")
remind me what is `from_int` and `to_int` in the `history` table again?  @pylipp

2024-03-18 15:33 UTC, pylipp commented on db/queries/annual_report.sql
> +    AND ((h.to_int IS NOT null AND h.id >= 1324559) OR h.changes = "Record created")
E.g. for a change box state, `changes` is `box_state_id`, and `from_int` / `to_int` the old/new value of the field.
On the opposite, for a change in a non-FK field like `comments`, `from_int` / `to_int` are null, and the changes are tracked in the `changes` field entirely (I'd prefer a `from_str`/`to_str` field at some point...).

Hence this condition selects all history entries related to FK-field (product, size, location) changes newer than 2023 and changes of number of items , and all "Record created" entries

2024-03-27 12:59 UTC, HaGuesto commented on db/queries/annual_report.sql
> +    "Shipment" AS target_type,
@pylipp This should follow the target_id column. Otherwise the union does not work and the results from this query are not in the same order as the other queries.

2024-04-05 09:52 UTC, HaGuesto approved these changes

2024-04-05 09:52 UTC, HaGuesto commented
@aerinsol can you merge it when you think it is ready?

2024-04-08 13:41 UTC, aerinsol requested changes
So, I have some concerns about the optimization of the CTEs as we start to process more data, especially as it appears that three of the CTEs are simply subqueries to create the BoxStateChangeVersions and CreateDonateBoxes temporary tables. I'd have to check the explain plan to be sure, but I imagine properly materilaizing the final "temporary" tables for re-use, and then dropping the previous CTEs from memory would scale much better. 

While I understand this is simply for the annual report and thus infrequent, I'm concernd that these optimization faults persist in StatViz . Some clarity in that department, and commented notes in the relevant code would be much appreciated.

2024-04-08 13:54 UTC, aerinsol commented
@pylipp if you could add the comments in the relevant areas above and confirm if it does or does not affect the StatViz queries, that would be most helpful. I imagine some of this is also @vahidbazzaz's work, so tagging him for visibility.

2024-04-11 06:00 UTC, pylipp commented
@aerinsol note added; the query here is almost identical to the one used for the moved-boxes statistic (here also base and org name info are selected), so I suppose statviz is affected to some degree

2024-04-11 07:23 UTC, aerinsol approved these changes

2024-04-11 07:23 UTC, merged